version: '3.8'

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      device: /home/luis/proyects/Inception/volumes
      o: bind
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: none
      device: /home/luis/proyects/Inception/volumes
      o: bind

networks:
  inception:
    name: inception

services:
  nginx:
    restart: always
    build: ./requirements/nginx/
    container_name: nginx
    image: nginx:42
    ports: 
      - 443:443
    networks: 
      - inception
    depends_on: 
      - wordpress
    volumes: 
     - wordpress:/var/www/html
    env_file:
      - .env
  wordpress:
    restart: always
    build: ./requirements/wordpress/
    image: wordpress:42
    container_name: wordpress
    depends_on: 
     - mariadb
    volumes: 
     - wordpress:/var/www/html
    env_file: .env
    networks: 
      - inception
  mariadb:
    restart: always
    build: ./requirements/mariadb/
    image: mariadb:42
    container_name: mariadb
    env_file: .env
    volumes: 
     - mariadb:/var/lib/mysql
    networks: 
      - inception





